### PR TITLE
Updated Utils class & started TC 1234

### PR DESCRIPTION
**Pull request by jika17**

### CODE REVIEW

**Review by emiryazicii — CHANGES_REQUESTED** [review]
Hey Jika thanks for making real good changes, can you please send the pull request to develop branch instead master branch.

**Comment by jika17** [comment]
Great, I was just going to ask you, Thanks

**Comment by emiryazicii** [comment]
You're welcome Jika.Glad to hear that help.

**Comment by jika17** [comment]
changed base to develop

**Comment by emiryazicii** [comment]
You , Farkhod and Nadia tried to make some changes in the same classes . So you join the conflict party as well . We will solve it tomorrow :)

**Review by Fleshka87 — APPROVED** [review]

**Review by emiryazicii — APPROVED** [review]
W solve the conflict.

**Pull request merged**
